# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

# version: 2
# registries:
#   codeartifact:
#     type: python-index
#     url: https://habitatenergy-479162328326.d.codeartifact.eu-west-2.amazonaws.com/pypi/habitatenergy/simple
#     username: aws
#     password: ${{secrets.CODEARTIFACT}}
#     replaces-base: true
# updates:
#   - package-ecosystem: "pip"
#     directory: "/"
#     insecure-external-code-execution: allow
#     registries:
#      - codeartifact
#     schedule:
#       interval: "weekly"
