version: 2
registries:
  dockerhub:
    type: docker-registry
    url: registry.hub.docker.com
    username: avsprashant
    password: ${{secrets.DOCKERHUB_PASSWORD}}
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries:
      - dockerhub
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
  - package-ecosystem: 'npm'
    directory: '/app'
    schedule:
      interval: 'daily'
