cronJob:
  enabled: true
  ## Runs every hour at the 25th and 55th minute, of every day, expect between 1-2am as there is a lack of data availability in that period
  schedule: "25,55 0,2-23 * * *"
  timeZone: "Europe/London"
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: forecast-da-train-predict
              image: 479162328326.dkr.ecr.eu-west-2.amazonaws.com/dayaheadforecaster
              version: 0.5.0
              env:
                - name: LOG_LEVEL
                  value: "INFO"
                - name: TAG
                  value: "dev"
                - name: DAY_AHEAD_FORECASTS_S3_BUCKET
                  value: "habitatenergy-dayaheadforecasts"
                - name: MARKET_DB_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: rds-dataconsumer-market-data-readonly
                      key: key
                - name: ELEXON_DB_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: rds-dataconsumer-elexon-push-readonly
                      key: key
                - name: FORECAST_DB_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: rds-forecast-readwrite
                      key: key
                ## Used to allow cross-account IAM role assumption for S3 access
                - name: AWS_PROFILE
                  value: "uk-prod"
                - name: AWS_CONFIG_FILE
                  value: /habitat/config/aws_config

              command: ["/bin/sh"]

              args: [
                "-c",
                "/habitat/.venv/bin/python3 -m habitatenergy.day_ahead_forecaster.train_predict --auction=HALF_HOURLY && /habitat/.venv/bin/python3 -m habitatenergy.day_ahead_forecaster.train_predict --auction=HOURLY"
              ]
              # Used to allow cross-account IAM role assumption for S3 access
              volumeMounts:
                - name: aws-config-file
                  mountPath: /habitat/config/

              resources:
                requests:
                  memory: "450Mi"
                  cpu: "100m"
                limits:
                  memory: "450Mi"
          ## Used to allow cross-account IAM role assumption for S3 access
          volumes:
            - name: aws-config-file
              configMap:
                name: forecast-da-train-predict-configmap

configMap:
  enabled: true
  data:
    aws_config: |
      [profile src]
      region=eu-west-2
      role_arn=arn:aws:iam::642966392923:role/forecast-da-train-predict-role
      web_identity_token_file=/var/run/secrets/eks.amazonaws.com/serviceaccount/token

      [profile uk-prod]
      role_arn=arn:aws:iam::479162328326:role/forecast-da-train-predict-dev-role
      source_profile=src
      region=eu-west-2

serviceAccount: 
  enabled: true
  metadata:
    additionalAnnotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::642966392923:role/forecast-da-train-predict-role
  secrets: 
    - rds-dataconsumer-market-data-readonly
    - rds-dataconsumer-elexon-push-readonly
    - rds-forecast-readwrite
