apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:                           
    app: {{ .Release.Name }}
type: Opaque
data:
  mongo_initdb_root_username: {{ .Values.database.username | b64enc | quote }}
  mongo_initdb_root_password: {{ .Values.database.password  | b64enc | quote }}
