apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      {{- if .Values.registry.private }}
      imagePullSecrets:
        - name: {{ .Values.registry.pullSecret }}
      {{- end}}
      containers:
        - name: {{ .Release.Name }}
          image: {{ printf "%s/%s:%s" .Values.registry.name .Values.image.name .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # envFrom:
          #   - configMapRef:
          #       name: {{ .Release.Name }}-config
          env:
            - name: TABLE
              value: {{ .Values.database.table }}
            - name: DB_URL
              value: mongodb://{{ .Values.database.username }}:{{ .Values.database.password }}@{{ .Release.Name }}:27017
          ports:
            - name: {{ .Values.service.port1.name }}
              containerPort: {{ .Values.service.port1.targetPort }}