apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.port1.name }}
      port: {{ .Values.service.port1.port }}
      targetPort: {{ .Values.service.port1.targetPort }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  