apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: charts/hello-world
    repoURL: https://github.com/helm/examples.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}

