name: buildingClibs
on: push

jobs:
  run-tests:
    name: testing
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: building
        run: |
          set -e
          sudo apt-get update -y && sudo apt-get install -y cmake wget
          pushd /tmp
          wget https://github.com/scipopt/soplex/archive/refs/tags/release-604.zip
          unzip release-604.zip
          mkdir /tmp/soplex-release-604/build/
          pushd /tmp/soplex-release-604/build/
          sudo cmake .. -DCMAKE_INSTALL_PREFIX=/opt/scip/
          sudo make
          ###
          popd
          wget https://github.com/scipopt/scip/archive/refs/tags/v803.zip
          unzip v803.zip
          mkdir /tmp/scip-803/build/
          pushd /tmp/scip-803/build/
          sudo cmake .. -DCMAKE_INSTALL_PREFIX=/opt/scip/ -DAUTOBUILD=on -DSOPLEX_DIR=/tmp/soplex-release-604/build
          sudo make
          sudo make install

      - name: Built targets
        shell: bash
        run: |
          set -e
          ls -lart /tmp/soplex-release-604/build/lib
          ls -lart /tmp/soplex-release-604/build/bin
          ls -lart /tmp/scip-803/build/lib
          ls -lart /tmp/scip-803/build/bin
          ls -lart /opt/scip/bin
          ls -lart /opt/scip/lib
