name: test
on: push

jobs:
  run-tests:
    name: testing
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: list packages
        run: apt list
        
      - name: number of packages
        run: apt list | wc -l
