name: My Workflow

on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 1
        uses: actions/checkout@v3

      - name: Checkout repository 2
        uses: actions/checkout@v3
        with:
          repository: octocat/Hello-World
          path: Hello-World

      - name: Do something with both repositories
        run: |
          echo "Repository contents: $(ls -lart /home/runner/work/mflabstest/mflabstest)"
