name: CI

on: [pull_request, push]

jobs:

  which_branch:
    runs-on: ubuntu-latest
    steps:
      - name: extract branch name on push event
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV; echo "HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV             

      - name: Get branch name
        run: echo 'The branch name is' ${{ env.BRANCH }}; echo 'hash is' ${{ env.HASH }}

      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mflabstest:${{ env.BRANCH }}-${{ env.HASH }
