name: simple image build

on: 
  push:
  workflow_dispatch:
    inputs:
      myInput:

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mflabstest:latest
